apiVersion: v1
kind: Pod
clusters:
  - cluster:
      certificate-authority: /var/run/kubernetes/ca.pem
metadata: 
  name: kube-controller
spec: 
  hostNetwork: true
  volumes:
    - name: "policies"
      hostPath:
        path: "/etc/kubernetes/policies"
    - name: "certs"
      hostPath:
        path: "/var/run/kubernetes"
  containers: 
    - name: "etcd"
      image: "b.gcr.io/kuar/etcd:2.1.1"
      args: 
        - "--data-dir=/var/lib/etcd"
        - "--advertise-client-urls=http://127.0.0.1:2379"
        - "--listen-client-urls=http://127.0.0.1:2379"
        - "--listen-peer-urls=http://127.0.0.1:2380"
        - "--name=etcd"
    - name: "kube-apiserver"
      volumeMounts:
        - name: "certs"
          mountPath: "/var/run/kubernetes"
          readOnly: true
        - name: "policies"
          mountPath: "/etc/kubernetes/policies"
          readOnly: true
      image: "gcr.io/google_containers/hyperkube-amd64:v1.2.0"
      args: 
        - "/hyperkube"
        - "apiserver"
        - "--allow-privileged=true"
        - "--etcd-servers=http://127.0.0.1:2379"
        - "--insecure-bind-address=0.0.0.0"
        - "--service-cluster-ip-range=10.200.20.0/24"
        - "--v=2"
    - name: "kube-controller-manager"
      volumeMounts:
        - name: "certs"
          mountPath: "/var/run/kubernetes"
          readOnly: true
      image: "gcr.io/google_containers/hyperkube-amd64:v1.2.0"
      args: 
        - "/hyperkube"
        - "controller-manager"
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
    - name: "kube-scheduler"
      volumeMounts:
        - name: "certs"
          mountPath: "/var/run/kubernetes"
          readOnly: true
      image: "gcr.io/google_containers/hyperkube-amd64:v1.2.0"
      args:
        - "/hyperkube"
        - "scheduler"
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
    - name: "kube-proxy"
      volumeMounts:
        - name: "certs"
          mountPath: "/var/run/kubernetes"
          readOnly: true
      image: "gcr.io/google_containers/hyperkube-amd64:v1.2.0"
      args:
        - "/hyperkube"
        - "proxy"
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
      securityContext:
        privileged: true
